"""Tests for P11 Markdown report output."""

import json
from pathlib import Path

from click.testing import CliRunner

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from main import audit
from mcp_audit.report import ReportGenerator


def _sample_results():
    return {
        'summary': {
            'total_dependencies': 1,
            'servers': 1,
            'tools': 0,
            'resources': 0,
            'vulnerabilities': 1,
            'quality_issues': 1,
            'transitive_deps': 2,
            'transitive_vulns': 1,
        },
        'dependencies': [
            {
                'name': 'filesystem',
                'type': 'server',
                'quality_score': 72,
                'vulnerabilities': [
                    {
                        'id': 'OSV-2026-123',
                        'severity': 'high',
                        'description': 'Example vulnerability',
                        'affected_versions': ['<1.2.0'],
                        'url': 'https://osv.dev/OSV-2026-123',
                        'dependency': 'filesystem',
                    }
                ],
                'maintenance_status': {'health': 'warning'},
                'trust_score': {
                    'score': 68,
                    'grade': 'B',
                    'quality': 72,
                    'security': 55,
                    'maintenance': 65,
                    'supply_chain': 70,
                    'transitive_risk_score': 35,
                    'transitive_risk_penalty': 10,
                },
                'transitive': {
                    'ecosystem': 'npm',
                    'total_deps': 2,
                    'max_depth': 1,
                    'vulnerable_deps': 1,
                    'risk_score': 35,
                    'tools_used': ['registry+osv'],
                    'dependencies': [
                        {
                            'name': 'left-pad',
                            'vulnerable': True,
                            'vulnerabilities': [
                                {'id': 'OSV-LEFTPAD-1', 'severity': 'medium'}
                            ],
                        }
                    ],
                },
            }
        ],
        'vulnerabilities': [
            {
                'id': 'OSV-2026-123',
                'severity': 'high',
                'description': 'Example vulnerability',
                'affected_versions': ['<1.2.0'],
                'url': 'https://osv.dev/OSV-2026-123',
                'dependency': 'filesystem',
            }
        ],
        'quality_issues': ['missing homepage'],
        'recommendations': [
            {
                'type': 'upgrade',
                'priority': 'high',
                'message': 'Upgrade filesystem server',
                'dependency': 'filesystem',
            }
        ],
    }


class TestMarkdownReportGenerator:
    def test_generate_markdown_report_contains_sections(self):
        report = ReportGenerator(_sample_results(), verbose=True).generate_markdown_report()

        assert '# 🔒 MCP Audit Report' in report
        assert '## 📊 Summary' in report
        assert '## 🛡️ Trust Score per Server' in report
        assert '## 🔗 Transitive Dependencies' in report
        assert '### Vulnerable Sub-Dependencies' in report
        assert '## 🚨 Vulnerabilities' in report
        assert '## 💡 Recommendations' in report
        assert '| filesystem | 🟡 68/100 | B |' in report
        assert 'https://osv.dev/OSV-2026-123' in report
        assert 'Generated by [mcp-audit](https://github.com/Mars375/mcp-audit)' in report

    def test_generate_markdown_report_omits_empty_optional_sections(self):
        results = _sample_results()
        results['vulnerabilities'] = []
        results['recommendations'] = []
        results['dependencies'][0].pop('transitive')
        results['dependencies'][0]['vulnerabilities'] = []

        report = ReportGenerator(results, verbose=False).generate_markdown_report()

        assert '## 🚨 Vulnerabilities' not in report
        assert '## 💡 Recommendations' not in report
        assert '## 🔗 Transitive Dependencies' not in report


class TestMarkdownCLI:
    def test_cli_writes_markdown_output_file(self, tmp_path):
        config_file = tmp_path / 'config.json'
        output_file = tmp_path / 'audit-report.md'
        config_file.write_text(json.dumps({'servers': {'empty-server': {}}}))

        runner = CliRunner()
        result = runner.invoke(audit, [
            '--config', str(config_file),
            '--format', 'markdown',
            '--output', str(output_file),
        ])

        assert result.exit_code == 0
        assert output_file.exists()
        content = output_file.read_text(encoding='utf-8')
        assert '# 🔒 MCP Audit Report' in content
        assert '## 📊 Summary' in content

    def test_project_config_can_set_markdown_format(self, tmp_path, monkeypatch):
        config_file = tmp_path / 'config.json'
        config_file.write_text(json.dumps({'servers': {'empty-server': {}}}))
        (tmp_path / '.mcp-audit.yaml').write_text(
            'format: markdown\noutput: configured-report.md\n',
            encoding='utf-8',
        )
        monkeypatch.chdir(tmp_path)

        runner = CliRunner()
        result = runner.invoke(audit, ['--config', str(config_file)])

        assert result.exit_code == 0
        output_file = tmp_path / 'configured-report.md'
        assert output_file.exists()
        assert 'Rapport Markdown genere' in result.output
        assert '# 🔒 MCP Audit Report' in output_file.read_text(encoding='utf-8')
